CREATE TABLE IF NOT EXISTS transactions (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    amount       NUMERIC(15,2) NOT NULL,
    deduction    NUMERIC(15,2) NOT NULL,
    allocated_to VARCHAR(20) NOT NULL,
    created_at   TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_transactions_user_date
ON transactions(user_id, created_at);